name: build
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Nuget/
    environment: Production
    steps:
    - name: Check out Code 
      uses: actions/checkout@v4
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build dotnet 
      run: dotnet build EntityFramework.Concurrency.sln --configuration release --no-restore
      
    - name: Run Tests
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Get CSProj Version
      id: PessimisticConcurrency_Abstractions
      uses: KageKirin/get-csproj-version@v1.0.0
      with:
        file: ./Nuget/PessimisticConcurrency.Abstractions/PessimisticConcurrency.Abstractions.csproj
            
    - name: Get CSProj Version
      id: PessimisticConcurrency
      uses: KageKirin/get-csproj-version@v1.0.0
      with:
        file: ./Nuget/PessimisticConcurrency/PessimisticConcurrency.csproj
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: ${{ steps.PessimisticConcurrency_Abstractions.outputs.version }}
        path: .

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: ${{ steps.PessimisticConcurrency.outputs.version }}
        path: .

