name: nuget-publish
on:
  workflow_dispatch:
    inputs:
      runId:
        description: Run ID
jobs:
  publish-nugets:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name:
          "PessimisticConcurrency.Abstractions"
        run-id:
          ${{ inputs.runId }}
        github-token:
          ${{ secrets.GITHUB_TOKEN }}

    - name: Restore dependencies
      run: dotnet restore Nuget/
      
    - name: Build dotnet 
      run: dotnet build Nuget/EntityFramework.Concurrency.sln --configuration release --no-restore
      
    - name: Package nuget
      run: dotnet pack Nuget/EntityFramework.Concurrency.sln --configuration release -o:package 
      
    - name: Push nuget to Nuget.Org
      run: dotnet nuget push package/*.nupkg --source https://api.nuget.org/v3/index.json

  #  - name: Push Nupkg to GitHub Packages
   #      # You may pin to the exact commit or the version.
   #       # uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@462b6006e5c90f732d030b0ace2c3e7ee9d550bc
  #    uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
   #   with:
    #    nupkg-path:  'package/*.nupkg'
    #    repo-owner:  'lukaskuko9'
   #     gh-user:  'lukaskuko9'
    #   token:  ${{secrets.NUGET_GITHUB_TOKEN}}

   # - name: Push generated package to GitHub registry
   #   run: dotnet nuget push ./package/*.nupkg -s $NUGET_SOURCE --api-key ${{secrets.NUGET_DEPLOY_TOKEN}}
   #   env:
   #     NUGET_SOURCE: "https://nuget.pkg.github.com/lukaskuko9/index.json"
